import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
const port = 8123;
const srv = spawn('python3', ['-m', 'http.server', String(port)], { cwd: '/home/user/tiletown', stdio: 'ignore' });
await new Promise(r => setTimeout(r, 800));
const browser = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const ctx = await browser.newContext({ viewport: { width: 412, height: 915 }, deviceScaleFactor: 2 });
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', e => errors.push(String(e)));
page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
const url = process.argv[2] || `http://localhost:${port}/dev.html?stats=1&zoom=4`;
await page.goto(url);
await page.waitForFunction(() => window.__tiletown && window.__tiletown.ready, null, { timeout: 60000 });
await page.waitForTimeout(1500);
const out = process.argv[3] || 'tools/measure-out/shot.png';
await page.screenshot({ path: out });
console.log('capture', out, 'erreurs', errors.length, errors.slice(0, 3));
await browser.close(); srv.kill();
